import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

/**
 * Generate a cryptographically secure 32-byte hex string
 * suitable for BETTER_AUTH_SECRET.
 */
export function generateSecret(): string {
  return crypto.randomBytes(32).toString('hex');
}

/**
 * Build the .env file content with all required variables.
 */
export function buildEnvContent(secret: string, dbUrl = 'mivo.db'): string {
  return [
    '# ==========================================',
    '# Mivo Next.js Environment Configuration',
    '# Generated by create-mivo',
    '# ==========================================',
    '',
    '# Database URL / SQLite File Path',
    `DATABASE_URL=${dbUrl}`,
    '',
    '# Better Auth Secret (32-byte cryptographic hex token)',
    `BETTER_AUTH_SECRET=${secret}`,
    '',
    '# Better Auth URL (Your application base URL)',
    'BETTER_AUTH_URL=http://localhost:3000',
    'NEXT_PUBLIC_APP_URL=http://localhost:3000',
    '',
  ].join('\n');
}

/**
 * Write the .env file to the project directory.
 * Returns the absolute path to the written file.
 */
export function writeEnvFile(projectDir: string, secret: string): string {
  const envPath = path.resolve(projectDir, '.env');
  const content = buildEnvContent(secret);
  fs.writeFileSync(envPath, content, 'utf8');
  return envPath;
}
